### ISSUE TITLE
shadow dissappear

### ISSUE THREAD

**Issue by creutzerb** [horde3d/Horde3D#196] opened 2021-10-14 08:34 UTC
Hi.

I have another case of shadows disappearing.

https://user-images.githubusercontent.com/10078731/137280236-06b06b60-f396-4096-a794-495ce00dadbb.mp4

It stops happening when the camera gets further.
```
<Light name="Spot01" lightingContext="LIGHTING" shadowContext="SHADOWMAP" fov="89" shadowMapBias="0.005" shadowMapCount="1" shadowSplitLambda="0" material="materials/light.material.xml" radius="25.0" colMult="1.3333333333333333" col_R="0.5656790137290955" col_G="0.39505836367607117" col_B="0.3053949177265167" tx="-7.00000" ty="8.00000" tz="19.00000" rx="270.00000" ry="0.00000"/>
```
Thanks.

**Comment by algts** [comment] 2021-10-15 18:47
I've reproduced the case in the editor, now trying to fix it. I thought that maybe camera znear had to do something with this problem, but it does not affect the shadows. I'll write when I have some results with the fix.

**Comment by algts** [comment] 2021-10-16 17:56
It seems that this problem directly relates to the earlier shadow issue #178 - if you revert the code in egRenderer.cpp line 1109 from 
```
float minZ = clamp( maxf( frustMinZ, bbMinZ ), -1, 1 );
```
to
```
float minZ = clamp( minf( frustMinZ, bbMinZ ), -1, 1 );
```

The problem will be gone. But it looks like you previous problem will surface again. Therefore, we have to somehow find out, in what cases should the first line be used and in what cases the second.

**Comment by creutzerb** [comment] 2021-10-17 00:40
I modified the end calcCropMatrix a bit to while looking at GPU gems, and it seems to be better. The only case where shadows disappear with the following code is when the object casting shadow leaves the screen. (like last video from my previous post)

(change minZ, scaleZ and offsetZ)
```
	float minX = clamp( maxf( frustMinX, bbMinX ), -1, 1 );
	float minY = clamp( maxf( frustMinY, bbMinY ), -1, 1 );
	float minZ = 0;
	float maxX = clamp( minf( frustMaxX, bbMaxX ), -1, 1 );
	float maxY = clamp( minf( frustMaxY, bbMaxY ), -1, 1 );
	float maxZ = clamp( minf( frustMaxZ, bbMaxZ ), -1, 1 );

	// Zoom-in slice to make better use of available shadow map space
	float scaleX = 2.0f / (maxX - minX);
	float scaleY = 2.0f / (maxY - minY);


	float offsetX = -0.5f * (maxX + minX) * scaleX;
	float offsetY = -0.5f * (maxY + minY) * scaleY;

	float scaleZ = 1.0f / (maxZ - minZ);
	float offsetZ = - minZ * scaleZ;
```
I kind of mindlessly tried to match what I was at [https://developer.nvidia.com/gpugems/gpugems3/part-ii-light-and-shadows/chapter-10-parallel-split-shadow-maps-programmable-gpus](url). Please note that I don't know much about this subject, and feel free to ignore what I said if that's just non-sense.

**Comment by algts** [comment] 2021-10-17 17:32
I'm also not a big specialist in shadow generation, so your approach may be valid. I'm currently looking at the problem when object is not seen by the camera and it's shadow disappear - I'm trying to verify whether shadow is registered in render views. May take some time.

**Comment by algts** [comment] 2021-10-18 20:02
I've pushed the fix to the develop branch. Works fine in the editor for 3 different lights on (to check disappearing shadow for one of the lights) and for one light close to the object (or at specific angle). If it works for you I'll create a patch release for Horde (2.0.1).
Thanks for pointing out the nasty error. Hope it works for you.

**Closed as completed** 2021-10-18 23:45 UTC
